name: ShortCMDS
version: 1.1
main: main.main

commands:
   gamemode:
      description: Du kannst dein und von anderen den Spielmodus verändern.
   gm:
      description: Du kannst dein und von anderen den Spielmodus verändern.
   spielmodus:
      description: Du kannst dein und von anderen den Spielmodus verändern.
   cmc:
      description: Du kannst deinen Chat löschen.
   löschemeinenchat:
      description: Du kannst deinen Chat löschen.
   heal:
      description: Du kannst dich undandere heilen.
   heilen:
      description: Du kannst dich und andere heilen.
   feed:
      description: Du kannst dich und andere füttern.
   füttern:
      description: Du kannst dich und andere füttern.
   playtime:
      description: Du kannst deine und von anderen die Spielzeit sehen.
   spielzeit:
      description: Du kannst deine und von anderen die Spielzeit sehen.
   clearmychat:
      description: Du kannst deinen Chat löschen.
   töte:
      description: Du kannst dich und andere umbringen.
   kill:
      description: Du kannst dich und andere umbringen.
   createconfig:
      description: Du kannst die Config erstellen oder resetten.
   fly:
      description: Du kannst fliegen.
   fliegen:
      description: Du kannst fliegen.
   shortcmds:
      description: Du bekommst Credits und Hilfe.    
